# Use new container infrastructure to enable caching
sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack.
matrix:
  include:
  - env: BUILD=stack RESOLVER=ghc-8.0
    language: generic
    addons: { apt: { packages: [ libgmp-dev ] } }
    compiler: ghc-8.0
  - env: BUILD=stack RESOLVER=ghc-8.2
    language: generic
    addons: { apt: { packages: [ libgmp-dev ] } }

  allow_failures:
  - env: BUILD=stack RESOLVER=ghc-8.2
    language: generic

install:
  - export PATH=$HOME/.local/bin::$HOME/.cabal/bin:$PATH
  - mkdir -p ~/.local/bin
  - |
    case "$BUILD" in
      stack)
        if [ `uname` = "Darwin" ]
        then
          travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
        else
          travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        fi
      ;;
    cabal)
      ;;
    esac

script:
- |
  set -ex
  if [ "x${RUNTEST}" = "xfalse" ]; then exit 0; fi
  case "$BUILD" in
    stack)
      rm stack.yaml && ln -sv .travis/stack-${RESOLVER}.yaml stack.yaml
      stack --no-terminal test \
          --flag foundation:bounds-check ${EXPERIMENTAL} \
          --install-ghc \
          --coverage --bench --no-run-benchmarks \
          --haddock --no-haddock-deps
      ;;
    cabal)
      cabal install --only-dependencies --enable-tests
      cabal test
      cabal check
      cabal sdist
      ;;
  esac
  set +ex
